version: '3'
services:

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: dblog
      MONGO_INITDB_ROOT_PASSWORD: ExceptSuddenMexicoFollowSunday48081
    networks:
      - nw_db_atc

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 4444:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: dblog
      ME_CONFIG_MONGODB_ADMINPASSWORD: ExceptSuddenMexicoFollowSunday48081
    networks:
      - nw_db_atc
    depends_on:
      - mongo
  
networks:
  nw_db_atc: